name: flutter_time_range
description: A fully customizable flutter widget that allowing users to choose time range (from - to) 
version: 0.0.3
homepage: https://github.com/alfanthariq/flutter_time_range

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  numberpicker: ^2.1.2
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
